version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: junvis-postgres
    restart: always
    environment:
      POSTGRES_DB: junvis_db
      POSTGRES_USER: junvis_user
      POSTGRES_PASSWORD: junvis_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U junvis_user -d junvis_db']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
